// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Wrapperizer.Sample.Infra.Persistence;

namespace Wrapperizer.Sample.Infra.Persistence.Migrations
{
    [DbContext(typeof(UniversityDbContext))]
    [Migration("20200610203627_InitializeDB")]
    partial class InitializeDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("uni")
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Wrapperizer.Sample.Domain.StudentAggregateRoot.RegistrationStatus", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100);

                    b.HasKey("Id");

                    b.ToTable("StudentStatus");
                });

            modelBuilder.Entity("Wrapperizer.Sample.Domain.StudentAggregateRoot.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("DateOfBirth")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasMaxLength(100)
                        .IsUnicode(true);

                    b.Property<int>("_registrationStatus")
                        .HasColumnName("RegistrationStatus")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("_registrationStatus");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Wrapperizer.Sample.Domain.StudentAggregateRoot.Student", b =>
                {
                    b.HasOne("Wrapperizer.Sample.Domain.StudentAggregateRoot.RegistrationStatus", "RegistrationStatus")
                        .WithMany()
                        .HasForeignKey("_registrationStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Wrapperizer.Sample.Domain.Common.NationalCode", "NationalCode", b1 =>
                        {
                            b1.Property<Guid>("StudentId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("_nationalCode")
                                .IsRequired()
                                .HasColumnName("NationalCode")
                                .HasColumnType("nvarchar(max)");

                            b1.HasKey("StudentId");

                            b1.ToTable("Students");

                            b1.WithOwner()
                                .HasForeignKey("StudentId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
